kind: pipeline
type: docker
name: default

steps:
  - name: deploy via ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      port:
        from_secret: ssh_port
      script:
        - cd ~/pms_demo_backend
        - ls
        - cp ../pms_backend_run.sh .
        - cp ../.env .
        - cp ../init.sql .
        - echo "copy done"
        - ./pms_backend_run.sh