services:
  backend:
    image: fishchuan/pms-demo-backend:latest
    container_name: pms-demo-backend
    build: .
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"
    restart: always
    networks:
      pms-backend-demo:
        ipv4_address: 10.0.3.2

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - pms-backend-demo:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
    networks:
      pms-backend-demo:
        ipv4_address: 10.0.3.3

volumes:
  pms-backend-demo:
    external: true

networks:
  pms-backend-demo:
    name: pms-backend-demo
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.3.0/25
          gateway: 10.0.3.1
