# Generated by Django 5.2 on 2025-05-05 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_number', models.CharField(blank=True, max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='profile')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, choices=[('yearly', 'YEARLY'), ('half-year', 'HALF-YEAR'), ('season', 'SEASON')])),
                ('plan_start', models.DateField()),
                ('plan_end', models.DateField()),
                ('is_activate', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
    ]
