# Generated by Django 5.2 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
