# Generated by Django 5.2 on 2025-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='card_number',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
