# Generated by Django 5.2 on 2025-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_member_username_member_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('yearly', 'YEARLY'), ('half-year', 'HALF-YEAR'), ('season', 'SEASON')]),
        ),
    ]
