# Generated by Django 5.2 on 2025-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member_card_number_alter_member_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
