# Generated by Django 5.2 on 2025-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='is_activate',
            field=models.BooleanField(default=False),
        ),
    ]
