# Generated by Django 5.2 on 2025-05-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plan_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_start',
            field=models.DateField(),
        ),
    ]
